#!/bin/bash

echo "INDI service installation script"

if [ $EUID = 0 ]; then

    #Copy files
    cp -v sbin/indiwebserver /usr/local/sbin/
    cp -v indiwebserver /etc/init.d/

    #Change privilages
    chmod 755 /usr/local/sbin/indiwebserver
    chmod 755 /etc/init.d/indiwebserver

    #Add service to system
    rc-update add indiwebserver default

else
    echo "You must be a root!!!"
fi

